### ISSUE TITLE
敏感词只有第一个生效

### ISSUE THREAD

**Issue by xiyou2014** [liuxueyong123/sensitive-word-tool#2]
sensitive-word-tool version: 1.1.7
chrome: 113.0.0.0
macbook pro 12.5.1 (Intel Core i7)

![image](https://github.com/liuxueyong123/sensitive-word-tool/assets/15934751/f2ad4697-fe48-4e42-99b1-2d5489bc46b4)
测试官网提供的demo，得到的结果与官网不一致

如果将敏感词单个通过 addWords 方法添加，表现才正常，如图
![image](https://github.com/liuxueyong123/sensitive-word-tool/assets/15934751/5c13c463-9fa5-447f-b0ae-426ae163a874)

**Comment by liuxueyong123** [comment]
我并没有复现你的问题，用你的代码跑出来的结果是正常的。你尝试用 node 跑一下看看是否有同样的问题呢
